### ISSUE TITLE
"Use your own inventory mode" has an error.

### ISSUE THREAD

**Issue by pelicano0** [dumbo-the-developer/Duels#17]
In "Use your own inventory mode," when dueling, there's a time limit, for example, 10 minutes. After 10 minutes, the players' items are deleted, and they are teleported to the lobby. This needs to be fixed.

**Comment by DropExitJoin** [comment]
Same, when using "own inventory" mode and game ends in a draw (time out), players inventory gets cleared

**Comment by dumbo-the-developer** [comment]
Fixed in new update
