### ISSUE TITLE
Teleport Delay Suggestion

### ISSUE THREAD

**Issue by pelicano0** [dumbo-the-developer/Duels#22]
I have a suggestion: the duel.match.teleport-delay setting should be enabled when item dropping is activated in use-own-inventory mode, or a specific teleport-delay setting should be added for use-own-inventory mode. When players duel with kits and item dropping is enabled in use-own-inventory mode, setting the teleport-delay to 15 causes both players dueling with kits and those using their own inventory to wait too long in the duel arena after the duel ends

**Comment by dumbo-the-developer** [comment]
teleport delay is already there. Multiple teleport delay makes no sense
