### ISSUE TITLE
XP Dupe

### ISSUE THREAD

**Issue by bobhenl** [dumbo-the-developer/Duels#31]
### Server version

Purpur 1.21.1

### Duels version

1.2

### Plugin list

not needed prob in this case

### Describe the bug

Hello, when you duel with someone & bring own XP bottles with option Use Own Inventory and throw them on the ground, then after the duel you have more XPs in your XP bar than before the duel + the XP bottles back.

### Expected behavior

No duping

### Steps to reproduce

1. Get XP bottles into your INV
2. /duel <player>
3. Choose Use Own Inventory
4. When duel starts, throw XP bottles on you
5. When duel ends, you'll have more XP in your XP bar + back the bottles

What's wrong?
That the XP bar isn't set to the initial stage before the duel (the same way as the inv etc. is)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by dumbo-the-developer** [comment]
Fixed in latest update
