### ISSUE TITLE
Items usage after match (Ender Pearl so you can stay in arena after duel ends)

### ISSUE THREAD

**Issue by bobhenl** [dumbo-the-developer/Duels#32]
### Server version

Purpur 1.21.1

### Duels version

1.2

### Plugin list

Not needed prob

### Describe the bug

Hello, you can consume the items after the duel ends (after you win), it takes a few seconds till you are teleported from the arena. Then there's issue that player can throw ender pearl & he doesn't get teleported away from arena then, because the pearl teleports him "back" to the arena. 

### Expected behavior

Disable consumable items / ender pearls & similar items after the duel ends (when you won the duel)

Or make configurable time to teleport player instantly after he wins (but he still can throw the ender pearl before killing the player & get bugged there, so there needs to be some workaround for it)

### Steps to reproduce

1. Enter duel with ender pearl kits / own inv with ender pearls
2. Win duel
3. After winning throw ender pearl (maybe try a few times, you prob need to throw it far enough or so)
4. If you throw it correctly, then you're likely to be teleported away from arena, but you won't be as the ender pearl teleports you back

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by dumbo-the-developer** [comment]
Fixed in latest update
