### ISSUE TITLE
Way to create own kit

### ISSUE THREAD

**Issue by bobhenl** [dumbo-the-developer/Duels#34]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

Currently, players need to choose from the existing kits, which isn't so good for them. Maybe they just wanna there 1 change in item, 1 different enchant, 1 different potion or so. This leads to server admins need to create bunch of kit variants with just small changes.

### Feature

The ideal thing would be to make possibility to create own kit, like some inv menu or creative menu (maybe in separate world), or maybe just typing in the chat / choosing from the menu. Or some other mechanism that can be seen on some duels or kit pvp servers. 

The idea is that player could make their own kits & choose this kit when sending request to a player.

### Alternatives

It would also be possible by doing '...'

**Comment by dumbo-the-developer** [comment]
You can enable duels with own inventory and give use any other kit plugin which allows the same. Players can get the kit and duel with their inventory

**Comment by bobhenl** [comment]
Oh so like make some separate world where they can make kit & then they can enter duel with this kit? Oh yeah, this could be the solution, thanks for the idea @dumbo-the-developer
