### ISSUE TITLE
OffHand Items being duped when using own inventory setting

### ISSUE THREAD

**Issue by ArberKulla** [dumbo-the-developer/Duels#40]
### Server version

Spigot 1.20.1

### Duels version

1.3

### Plugin list

>[23:50:03] [Server thread/INFO] [/]: Plugins (42): LuckPerms, OpenInv, XRayDetector, PlaceholderAPI, ClearLag, DisableCommands, PlayTime, ConsoleSpamFix, ProtocolLib, VotifierPlus, SkinsRestorer, BlueSlimeCore, Tebex, BountySeekers, AntiChatManager, AntiCurse, StaffChat, NBTAPI, Vault, SRV-Cron, WorldEdit, DecentHolograms, Essentials, WithdrawPlugin, WorldGuard, TradeSystem, EssentialsChat, BanItem, TAB, EssentialsSpawn, WorldGuardEvents, CoreProtect, AuthMe, Towny, TownyChat, VotingPlugin, DiscordSRV, BetterRTP, CombatLogX, ShopGUIPlus, JJKArai, Duels

### Describe the bug

You can dupe your offhand item with duels if your using your own inventory

### Expected behavior

Your not supposed to dupe items

### Steps to reproduce

Step 1: Enter duel with item in off hand
Step 2: During duel, remove item from off hand
Step 3: Die
Step 4: Now after the duel, you will get the item back to your off hand, even though you took it off, and keep the one in your inventory. Duplicating it

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by dumbo-the-developer** [comment]
fixed in latest commit. ill update plugin soon
