### ISSUE TITLE
Maintaining kit items after the duel is over

### ISSUE THREAD

**Issue by ArberKulla** [dumbo-the-developer/Duels#41]
### Server version

Spigot 1.20.1

### Duels version

1.3

### Plugin list

>[23:50:03] [Server thread/INFO] [/]: Plugins (42): LuckPerms, OpenInv, XRayDetector, PlaceholderAPI, ClearLag, DisableCommands, PlayTime, ConsoleSpamFix, ProtocolLib, VotifierPlus, SkinsRestorer, BlueSlimeCore, Tebex, BountySeekers, AntiChatManager, AntiCurse, StaffChat, NBTAPI, Vault, SRV-Cron, WorldEdit, DecentHolograms, Essentials, WithdrawPlugin, WorldGuard, TradeSystem, EssentialsChat, BanItem, TAB, EssentialsSpawn, WorldGuardEvents, CoreProtect, AuthMe, Towny, TownyChat, VotingPlugin, DiscordSRV, BetterRTP, CombatLogX, ShopGUIPlus, JJKArai, Duels

### Describe the bug

You keep the kits items after the duel is over, if they are in a slot where you previously did not have an item.

### Expected behavior

You don't keep the kits item

### Steps to reproduce

Step 1: Enter duel with empty inv
Step 2: Play a kit duel
Step 3: Die and lose
Step 4: Now you have the kit items in your inv 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by dumbo-the-developer** [comment]
Is `clear-items-after-duel` set to true in your config?

**Comment by dumbo-the-developer** [comment]
fixed in latest commit. Ill release update soon
