### ISSUE TITLE
An error while using command /duels

### ISSUE THREAD

**Issue by youge-grass** [dumbo-the-developer/Duels#47]
### Server version

paper 1.21.1

### Duels version

1.6

### Plugin list

![image](https://github.com/user-attachments/assets/aa884e92-6179-4eb2-951d-9bae50728644)

### Describe the bug

![image](https://github.com/user-attachments/assets/27a030ff-940b-4556-9eb6-e1bae8987c21)

### Expected behavior

Show GUI of duels

### Steps to reproduce

1./duel *someone*
2.This bug appears

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by dumbo-the-developer** [comment]
You have error in your configuration please check it

**Comment by youge-grass** [comment]
Oh I delete the yml and restart it works <3 thanks!Also how does the start_command works? where should I add my commands?
