### ISSUE TITLE
[bug] a very annoy bug with stats

### ISSUE THREAD

**Issue by F3F5** [dumbo-the-developer/Duels#6]
sometimes writes “can't load stats” duels when logging in to the server

**Comment by dumbo-the-developer** [comment]
Fixed

**Comment by F3F5** [comment]
wich commit

**Comment by dumbo-the-developer** [comment]
Pushing in few minutes. Also please delete the old playerdata file which is corrupted

**Comment by F3F5** [comment]
it's random, you log back in and everything's fine, so I don't think there's anything wrong with the file.

**Comment by F3F5** [comment]
https://github.com/dumbo-the-developer/Duels/commit/99ac1d8f1a67ee97bbd53ee06ec01271de6c6fb9
Has anything changed other than the style of the code?

**Comment by dumbo-the-developer** [comment]
Some other guys reporting it's permanent

**Comment by dumbo-the-developer** [comment]
Try the latest update and check if the issue still persist
